routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AboutUsController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\HealthBenefitController;
use App\Http\Controllers\Admin\IngredientController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\WellbeingController;
use App\Http\Controllers\CKeditorController;
use App\Http\Controllers\Frontend\FrontendController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/test', function () {
    return view('back-end.dashboard');
});

Route::group(['as' => 'front_end.'], function () {
    Route::get('/', [FrontendController::class, 'home'])->name('home');
    Route::get('/drinks', [FrontendController::class, 'products'])->name('drinks');
    Route::get('/drink/{slug}', [FrontendController::class, 'product_detail'])->name('drinks.detail');
    Route::get('/stores', [FrontendController::class, 'store'])->name('stores');
    Route::get('/vibe', [FrontendController::class, 'vibe'])->name('vibe');
    Route::get('/about-us', [FrontendController::class, 'about_us'])->name('about_us');
    Route::get('/contact-us', [FrontendController::class, 'contact'])->name('contact');
    Route::get('/jobs', [FrontendController::class, 'jobs'])->name('jobs');

    Route::get('/privacy-policy', [FrontendController::class, 'privacy'])->name('privacy_policy');
    Route::get('/terms-and-conditions', [FrontendController::class, 'term_and_condition'])->name('term');

    Route::group(['prefix' => 'news'], function () {
        Route::get('/', [FrontendController::class, 'posts'])->name('news.index');
        Route::get('/{slug}', [FrontendController::class, 'postShow'])->name('news.detail');
    });

    Route::group(['prefix' => 'wellbeing'], function () {
        Route::get('/', [FrontendController::class, 'wellbeing'])->name('wellbeing.index');
        Route::get('/{slug}', [FrontendController::class, 'wellbeing_detail'])->name('wellbeing.detail');
    });

    Route::group(['prefix' => 'franchising', 'as' => 'franchising.'], function () {
        Route::get('/', [FrontendController::class, 'franchising'])->name('index');
    });
});


Route::group(['middleware' => ['auth'], 'prefix' => 'dashboard', 'as' => 'admin.'], function () {
    Route::get('/', function () {
        return view('back-end.dashboard');
    })->name('dashboard');
    Route::resource('categories', CategoryController::class);
    Route::resource('benefits', HealthBenefitController::class);
    Route::resource('ingredients', IngredientController::class);
    Route::resource('products', ProductController::class);
    Route::resource('posts', PostController::class);
    Route::resource('wellbeing', WellbeingController::class);
    Route::resource('about', AboutUsController::class);
    Route::resource('users', UserController::class);

    Route::get('profile', [ProfileController::class, 'profile'])->name('profile');
    Route::put('profile', [ProfileController::class, 'update_profile'])->name('profile.update');
    Route::post('password', [ProfileController::class, 'change_password'])->name('profile.change_password');

    Route::resource('settings', SettingController::class)->except(['delete']);

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {

        Route::get('{page}/setting', [PageController::class, 'index'])->name('index');
        Route::put('{page}/setting', [PageController::class, 'update'])->name('update');

        Route::get('/vibe', [PageController::class, 'vibe_page'])->name('vibe');
        Route::put('/vibe', [PageController::class, 'update_vibe_page'])->name('vibe.update');

        Route::resource('{page}/faq', FaqController::class);
    });
});

Route::post('ckeditor/upload', [CKeditorController::class, 'upload'])->name('ckeditor.image-upload');


Auth::routes([
    'login' => true,
    'register' => false,
    'reset' => false
]);

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Product extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = ['id'];

    protected $casts = [
        'images' => 'array',
    ];

    protected $attributes = [
        "images" => [
            "main_image" => "2022-02-04-61fcaff531620.png",
            "thumbnail_image" => "2022-02-04-61fcaff531c1d.png",
            "cup_shadow_image" => "2022-02-04-61fcaff532176.png",
            "ingredient_image" => "2022-02-04-61fcaff532754.png"
        ]
    ];

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = Str::title($value);
        $this->attributes['slug'] = preg_replace('/\s+/u', '-', trim(Str::lower($value)));
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class, 'product_category');
    }

    public function ingredients()
    {
        return $this->belongsToMany(Ingredient::class, 'product_ingredient');
    }

    public function benefits()
    {
        return $this->belongsToMany(HealthBenefit::class, 'product_health_benefit', 'product_id', 'health_benefit_id');
    }

    public function getFullImageURLAttribute()
    {
        $images = [];
        foreach ($this->images as $key => $image) {
            $images[$key] = asset('images/' . $image);
        }
        return $images;
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateProductRequest;
use App\Http\Requests\StoreProductRequest;
use App\Http\Traits\ImageUploadTrait;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    use ImageUploadTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('id', 'desc')->paginate(10);
        return view('back-end.products.index', [
            'products' => $products
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product = new Product();
        return view('back-end.products.create', [
            'product' => $product
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        $product = Product::create([
            'name' => $request->name,
            'description' => $request->description,
            'status' => isset($request->status)
        ]);

        $categories = $request->categories;
        $ingredients = $request->ingredients;
        $benefits = $request->benefits;

        if (is_array($categories)) {
            $product->categories()->attach($categories);
        }
        if (is_array($ingredients)) {
            $product->ingredients()->attach($ingredients);
        }
        if (is_array($benefits)) {
            $product->benefits()->attach($benefits);
        }
        $imagUpdate = $product->images;

        $main_image = $request->file('main_image');
        $thumbnail_image = $request->file('thumbnail_image');
        $cup_shadow_image = $request->file('cup_shadow_image');
        $ingredient_image = $request->file('ingredient_image');
        if ($main_image) {
            $imagUpdate['main_image'] = $this->updateImage($imagUpdate['main_image'] ?? 'no.jpg', $main_image);
        }
        if ($thumbnail_image) {
            $imagUpdate['thumbnail_image'] = $this->updateImage($imagUpdate['thumbnail_image'] ?? 'no.jpg', $thumbnail_image);
        }
        if ($cup_shadow_image) {
            $imagUpdate['cup_shadow_image'] = $this->updateImage($imagUpdate['cup_shadow_image'] ?? 'no.jpg', $cup_shadow_image);
        }
        if ($ingredient_image) {
            $imagUpdate['ingredient_image'] = $this->updateImage($imagUpdate['ingredient_image'] ?? 'no.jpg', $ingredient_image);
        }
        $product->update(['images' => $imagUpdate]);
        return redirect()->route('admin.products.index')->with('success', 'Product created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect()->route('admin.products.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $product = $product->load(['categories', 'ingredients', 'benefits']);
        return view('back-end.products.edit', [
            'product' => $product
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $product->update([
            'name' => $request->name,
            'description' => $request->description,
            'status' => isset($request->status)
        ]);
        $categories = $request->categories;
        $ingredients = $request->ingredients;
        $benefits = $request->benefits;

        if (is_array($categories)) {
            $product->categories()->sync($categories);
        }

        if (is_array($ingredients)) {
            $product->ingredients()->sync($ingredients);
        }
        if ($benefits && is_array($benefits)) {
            $product->benefits()->sync($benefits);
        }
        $imagUpdate = $product->images;

        $main_image = $request->file('main_image');
        $thumbnail_image = $request->file('thumbnail_image');
        $cup_shadow_image = $request->file('cup_shadow_image');
        $ingredient_image = $request->file('ingredient_image');
        if ($main_image) {
            $imagUpdate['main_image'] = $this->updateImage($imagUpdate['main_image'] ?? 'no.jpg', $main_image);
        }
        if ($thumbnail_image) {
            $imagUpdate['thumbnail_image'] = $this->updateImage($imagUpdate['thumbnail_image'] ?? 'no.jpg', $thumbnail_image);
        }
        if ($cup_shadow_image) {
            $imagUpdate['cup_shadow_image'] = $this->updateImage($imagUpdate['cup_shadow_image'] ?? 'no.jpg', $cup_shadow_image);
        }
        if ($ingredient_image) {
            $imagUpdate['ingredient_image'] = $this->updateImage($imagUpdate['ingredient_image'] ?? 'no.jpg', $ingredient_image);
        }
        $product->update(['images' => $imagUpdate]);
        return redirect()->route('admin.products.index')->with('success', 'Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('admin.products.index')->with('success', 'Product deleted successfully');
    }
}

resources/views/back-end/products/create.blade.php
@extends('back-end.layout.app')

@section('title,14 Feb','Add Drink')

@push('css')
    <link href="{{ asset('admin/vendor/select2/dist/css/select2.min.css')}} " rel="stylesheet">
    <style>
        .is-invalid {
            border: 2px solid #dc3545 !important;
        }
    </style>
@endpush

@section('content')
    <div id="content">

        <div class="container-fluid" id="container-wrapper">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Add Product</h1>
                <ol class="breadcrumb">
                    <a href="{{ route('admin.products.index') }}" class="btn btn-primary">All Products</a>
                </ol>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <!-- Form Basic -->
                    <div class="card mb-4">
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">Add Product</h6>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('admin.products.store') }}"
                                  enctype="multipart/form-data">
                                @csrf
                                <div class="form-row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="validationServer03">Product Name</label>
                                            <input type="text" name="name" value="{{ old('name') }}"
                                                   class="form-control  @error('name') is-invalid @enderror">
                                            @error('name')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group form-select2">
                                            <label for="category">Category</label>
                                            <select
                                                class="select2-multiple form-control select2-category   @error('categories') is-invalid @enderror"
                                                name="categories[]"
                                                multiple="multiple"
                                                id="category">
                                                @foreach($categories as $category)
                                                    <option
                                                        {{ in_array((string)$category->id,old('categories',[]) ) ? 'selected' : ''  }}
                                                        value="{{ $category->id }}">{{ $category->name }}</option>
                                                @endforeach
                                            </select>
                                            @error('categories')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                            @enderror
                                        </div>
                                        <br>
                                    </div>
                                </div>

                                <div class="form-row">
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="ingredient">Ingredient</label>
                                            <select
                                                class="select2-multiple form-control select2-ingredient  @error('ingredients') is-invalid @enderror"
                                                name="ingredients[]"
                                                multiple="multiple"
                                                id="ingredient">
                                                @foreach($ingredients as $ingredient)
                                                    <option
                                                        {{ in_array((string)$ingredient->id,old('ingredients',[]) ) ? 'selected' : ''  }}
                                                        value="{{ $ingredient->id }}">{{ $ingredient->name }}</option>
                                                @endforeach
                                            </select>
                                            @error('ingredients')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group">
                                            <label for="benefit">Benefit</label>
                                            <select
                                                class="select2-multiple form-control select2-benefit  @error('benefits') is-invalid @enderror"
                                                name="benefits[]"
                                                multiple="multiple"
                                                id="benefit">
                                                @foreach($benefits as $benefit)
                                                    <option
                                                        {{ in_array((string)$benefit->id,old('benefits',[]) ) ? 'selected' : ''  }}
                                                        value="{{ $benefit->id }}">{{ $benefit->name }}</option>
                                                @endforeach
                                            </select>
                                            @error('benefits')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                            @enderror
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="validationServer03">Product Description</label>
                                    <textarea class="form-control @error('description') is-invalid @enderror"
                                              name="description" id="description" cols="30"
                                              rows="5">{{ old('description') }}</textarea>
                                    @error('description')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                                <div class="clearfix"></div>
                                <div class="form-group">
                                    <div class="form-row">
                                        <div class="col">
                                            <div class="custom-file">
                                                <input type="file" class="custom-file-input images" name="main_image"
                                                       id="main_image" data-preview="#main_image_image">
                                                <label class="custom-file-label" for="main_image">Main Image</label>
                                            </div>
                                            <img class="img-thumbnail mt-3"
                                                 src="{{ asset('img/placeholders/product/main_image.png') }}"
                                                 id="main_image_image"
                                                 alt="Image Preview">
                                        </div>
                                        <div class="col">
                                            <div class="custom-file">
                                                <input type="file" class="custom-file-input images"
                                                       name="thumbnail_image"
                                                       id="thumbnail_image" data-preview="#thumbnail_image_preview">
                                                <label class="custom-file-label" for="thumbnail_image">Thumbnail</label>
                                            </div>
                                            <img class="img-thumbnail mt-3"
                                                 src="{{ asset('img/placeholders/product/thumbnail_image.png') }}"
                                                 id="thumbnail_image_preview"
                                                 alt="Image Preview">

                                        </div>
                                        <div class="col">
                                            <div class="custom-file">
                                                <input type="file" class="custom-file-input images"
                                                       name="cup_shadow_image"
                                                       id="cup_shadow_image" data-preview="#cup_shadow_image_preview">
                                                <label class="custom-file-label" for="cup_shadow_image">Cup Shadow
                                                    Image</label>
                                            </div>
                                            <img class="img-thumbnail mt-3"
                                                 src="{{ asset('img/placeholders/product/cup_shadow_image.png') }}"
                                                 id="cup_shadow_image_preview"
                                                 alt="Image Preview">

                                        </div>
                                        <div class="col">
                                            <div class="custom-file">
                                                <input type="file" class="custom-file-input images"
                                                       name="ingredient_image"
                                                       data-preview="#ingredient_image_image"
                                                       id="ingredient_image">
                                                <label class="custom-file-label" for="ingredient_image">Ingredient
                                                    Image</label>
                                            </div>
                                            <div class="invalid-feedback">
                                                ffffff
                                            </div>
                                            <img class="img-thumbnail mt-3"
                                                 src="{{ asset('img/placeholders/product/ingredient_image.png') }}"
                                                 id="ingredient_image_image"
                                                 alt="Image Preview">
                                        </div>
                                    </div>

                                </div>
                                <div class="form-group">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" name="status" checked class="custom-control-input"
                                               id="status">
                                        <label class="custom-control-label" for="status">Status</label>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
            <!--Row-->

        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('admin/vendor/select2/dist/js/select2.min.js') }}"></script>
    <script>
        // Select2
        $('.select2-category').select2({
            allowClear: true,
            placeholder: "Select Category",
        });
        $('.select2-ingredient').select2({
            allowClear: true,
            placeholder: "Select Ingredient",
        });
        $('.select2-benefit').select2({
            allowClear: true,
            placeholder: "Select health benefits",
        });
    </script>
    <script src="{{ asset('admin/js/image-preview.js') }}"></script>
@endpush

resources/views/back-end/products/index.blade.php
@extends('back-end.layout.app')


@section('title,14 Feb','All Products')

@push('css')

@endpush


@section('content')
    <div id="content">
        <div class="container-fluid" id="container-wrapper">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">All Products</h1>
                <ol class="breadcrumb">
                    <a href="{{ route('admin.products.create') }}" class="btn btn-primary">New Product</a>
                </ol>
            </div>

            <div class="row">
                <div class="col-lg-12 mb-4">
                    <!-- Simple Tables -->
                    <div class="card">
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">All Drinks</h6>
                        </div>
                        <div class="table-responsive">
                            <table class="table align-items-center table-flush">
                                <thead class="thead-light">
                                <tr>
                                    <th>#</th>
                                    <th>Main Image</th>
                                    <th>Name</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($products as $product)
                                    <tr>
                                        <td class="align-middle">{{ ++$loop->index }}</td>
                                        <td><img src="{{ $product->full_image_url['main_image'] }}" alt="Image"
                                                 class="img-thumbnail" width="70"></td>
                                        <td class="align-middle">{{ $product->name }}</td>
                                        <td class="align-middle">
                                            @if($product->status ==1 )
                                                <span class="badge badge-success">active</span>
                                            @else
                                                <span class="badge badge-danger">inactive</span>
                                            @endif

                                        </td>
                                        <td class="align-middle">
                                            <a href="{{ route('admin.products.edit', $product->id) }}"
                                               class="btn btn-sm btn-primary">Edit</a>
                                            <a onclick="if(confirm('Are you sure?')){
                                                document.getElementById('delete-{{$product->id}}').submit()
                                                }" class="btn btn-sm btn-danger">Delete</a>
                                        </td>
                                        <form method="POST" id="delete-{{ $product->id }}" class="hidden"
                                              action="{{ route('admin.products.destroy',$product) }}">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </tr>
                                @empty
                                    <tr class="text-center">
                                        <th colspan="20">No data found</th>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                        <div class="card-footer">
                            {{ $products->links('back-end.layout.partials.pagination') }}
                        </div>
                    </div>
                </div>
            </div>
            <!--Row-->

            <!-- Modal Logout -->
            <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog"
                 aria-labelledby="exampleModalLabelLogout" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabelLogout">Ohh No!</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure you want to logout?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Cancel</button>
                            <a href="login.html" class="btn btn-primary">Logout</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection