routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AboutUsController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\HealthBenefitController;
use App\Http\Controllers\Admin\IngredientController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\WellbeingController;
use App\Http\Controllers\CKeditorController;
use App\Http\Controllers\Frontend\FrontendController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/test', function () {
    return view('back-end.dashboard');
});

Route::group(['as' => 'front_end.'], function () {
    Route::get('/', [FrontendController::class, 'home'])->name('home');
    Route::get('/drinks', [FrontendController::class, 'products'])->name('drinks');
    Route::get('/drink/{slug}', [FrontendController::class, 'product_detail'])->name('drinks.detail');
    Route::get('/stores', [FrontendController::class, 'store'])->name('stores');
    Route::get('/vibe', [FrontendController::class, 'vibe'])->name('vibe');
    Route::get('/about-us', [FrontendController::class, 'about_us'])->name('about_us');
    Route::get('/contact-us', [FrontendController::class, 'contact'])->name('contact');
    Route::get('/jobs', [FrontendController::class, 'jobs'])->name('jobs');

    Route::get('/privacy-policy', [FrontendController::class, 'privacy'])->name('privacy_policy');
    Route::get('/terms-and-conditions', [FrontendController::class, 'term_and_condition'])->name('term');

    Route::group(['prefix' => 'news'], function () {
        Route::get('/', [FrontendController::class, 'posts'])->name('news.index');
        Route::get('/{slug}', [FrontendController::class, 'postShow'])->name('news.detail');
    });

    Route::group(['prefix' => 'wellbeing'], function () {
        Route::get('/', [FrontendController::class, 'wellbeing'])->name('wellbeing.index');
        Route::get('/{slug}', [FrontendController::class, 'wellbeing_detail'])->name('wellbeing.detail');
    });

    Route::group(['prefix' => 'franchising', 'as' => 'franchising.'], function () {
        Route::get('/', [FrontendController::class, 'franchising'])->name('index');
    });
});


Route::group(['middleware' => ['auth'], 'prefix' => 'dashboard', 'as' => 'admin.'], function () {
    Route::get('/', function () {
        return view('back-end.dashboard');
    })->name('dashboard');
    Route::resource('categories', CategoryController::class);
    Route::resource('benefits', HealthBenefitController::class);
    Route::resource('ingredients', IngredientController::class);
    Route::resource('products', ProductController::class);
    Route::resource('posts', PostController::class);
    Route::resource('wellbeing', WellbeingController::class);
    Route::resource('about', AboutUsController::class);
    Route::resource('users', UserController::class);

    Route::get('profile', [ProfileController::class, 'profile'])->name('profile');
    Route::put('profile', [ProfileController::class, 'update_profile'])->name('profile.update');
    Route::post('password', [ProfileController::class, 'change_password'])->name('profile.change_password');

    Route::resource('settings', SettingController::class)->except(['delete']);

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {

        Route::get('{page}/setting', [PageController::class, 'index'])->name('index');
        Route::put('{page}/setting', [PageController::class, 'update'])->name('update');

        Route::get('/vibe', [PageController::class, 'vibe_page'])->name('vibe');
        Route::put('/vibe', [PageController::class, 'update_vibe_page'])->name('vibe.update');

        Route::resource('{page}/faq', FaqController::class);
    });
});

Route::post('ckeditor/upload', [CKeditorController::class, 'upload'])->name('ckeditor.image-upload');


Auth::routes([
    'login' => true,
    'register' => false,
    'reset' => false
]);

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Ingredient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Ingredient extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = ['id'];


    public function getRouteKeyName()
    {
        return 'slug';
    }



    public function products()
    {
        return $this->belongsToMany(Product::class, 'ingredient_id', 'product_id');
    }

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = Str::title($value);
        $this->attributes['slug'] = preg_replace('/\s+/u', '-', trim(Str::lower($value)));
    }
}

app/Http/Controllers/Admin/IngredientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\IngredientRequest;
use App\Http\Traits\ImageUploadTrait;
use App\Models\Ingredient;

class IngredientController extends Controller
{
    use ImageUploadTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ingredients = Ingredient::orderBy('id', 'desc')->paginate(10);
        return view('back-end.ingredients.index', [
            'ingredients' => $ingredients
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ingredient = new Ingredient();
        return view('back-end.ingredients.create', [
            'ingredient' => $ingredient
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(IngredientRequest $request)
    {
        Ingredient::create([
            'name' => $request->name,
        ]);
        return redirect()->route('admin.ingredients.index')->with('success', 'Ingredient created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect()->route('admin.ingredients.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Ingredient $ingredient)
    {
        return view('back-end.ingredients.edit', [
            'ingredient' => $ingredient
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(IngredientRequest $request, Ingredient $ingredient)
    {

        $ingredient->update([
            'name' => $request->name,
        ]);
        return redirect()->route('admin.ingredients.index')->with('success', 'Ingredient updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ingredient $ingredient)
    {
        $ingredient->delete();
        return redirect()->route('admin.ingredients.index')->with('success', 'Ingredient deleted successfully');
    }
}

resources/views/back-end/ingredients/create.blade.php
@extends('back-end.layout.app')


@section('title,14 Feb','Add Ingredient')

@section('content')
    <div id="content">
        <div class="container-fluid" id="container-wrapper">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">New Ingredient</h1>
                <ol class="breadcrumb">
                    <a href="{{ route('admin.ingredients.index') }}" class="btn btn-primary">All Ingredients</a>
                </ol>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <!-- Form Basic -->
                    <div class="card mb-4">
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">New Ingredient</h6>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('admin.ingredients.store') }}"
                                  enctype="multipart/form-data">
                                @csrf
                                @include('back-end.ingredients.form')
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
            <!--Row-->
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('admin/js/image-preview.js') }}"></script>
@endpush

resources/views/back-end/ingredients/edit.blade.php
@extends('back-end.layout.app')


@section('title,14 Feb','Add Ingredient')

@section('content')
    <div id="content">
        <div class="container-fluid" id="container-wrapper">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Edit Benefit</h1>
                <ol class="breadcrumb">
                    <a href="{{ route('admin.ingredients.index') }}" class="btn btn-primary">All Ingredients</a>
                </ol>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <!-- Form Basic -->
                    <div class="card mb-4">
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">Edit Ingredient</h6>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('admin.ingredients.update', $ingredient) }}"
                                  enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                @include('back-end.ingredients.form')
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
            <!--Row-->
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('admin/js/image-preview.js') }}"></script>
@endpush

resources/views/back-end/ingredients/form.blade.php
<div class="form-group">
    <label for="validationServer03">Name</label>
    <input type="text" name="name"
           class="form-control  @error('name') is-invalid @enderror" value="{{ old('name', $ingredient->name) }}">
    @error('name')
    <div class="invalid-feedback">
        {{ $message }}
    </div>
    @enderror
</div>

{{--<div class="form-group">--}}
{{--    <div class="custom-file">--}}
{{--        <input type="file" name="image" class="custom-file-input @error('image') is-invalid @enderror" id="image">--}}
{{--        <label class="custom-file-label" for="customFile">Image</label>--}}
{{--        @error('image')--}}
{{--        <div class="invalid-feedback">--}}
{{--            {{ $message }}--}}
{{--        </div>--}}
{{--        @enderror--}}
{{--    </div>--}}

{{--</div>--}}

{{--<div class="form-group">--}}
{{--    <img class="img-fluid bg-gradient-success mt-3 mb-3" width="80" src="{{ asset('images/' . $ingredient->image) }}" alt="Image Preview"--}}
{{--         id="preview-image">--}}
{{--</div>--}}

resources/views/back-end/ingredients/index.blade.php
@extends('back-end.layout.app')


@section('title,14 Feb','All Drinks')


@section('content')
    <div id="content">
        <div class="container-fluid" id="container-wrapper">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">All Ingredients</h1>
                <ol class="breadcrumb">
                    <a href="{{ route('admin.ingredients.create') }}" class="btn btn-primary">New Ingredient</a>
                </ol>
            </div>

            <div class="row">
                <div class="col-lg-12 mb-4">
                    <!-- Simple Tables -->
                    <div class="card">
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">All Ingredients</h6>
                        </div>
                        <div class="table-responsive">
                            <table class="table align-items-center table-flush">
                                <thead class="thead-light">
                                <tr>
                                    <th>#</th>
{{--                                    <th>Image</th>--}}
                                    <th>Name</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($ingredients as $ingredient)
                                    <tr>
                                        <td class="align-middle">{{ ++$loop->index }}</td>
{{--                                        <td>--}}
{{--                                            <img class="img-thumbnail bg-gradient-success" width="60"--}}
{{--                                                 src="{{ asset('images/' . $ingredient->image) }}"--}}
{{--                                                 alt="Image">--}}
{{--                                        </td>--}}
                                        <td class="align-middle">{{ $ingredient->name}}</td>
                                        <td class="align-middle">
                                            <a href="{{ route('admin.ingredients.edit', $ingredient) }}"
                                               class="btn btn-sm btn-primary">Edit</a>
                                            <a onclick="if(confirm('Are you sure?')){
                                                document.getElementById('delete-{{$ingredient->id}}').submit()
                                                }" class="btn btn-sm btn-danger">Delete</a>
                                        </td>
                                        <form method="POST" id="delete-{{ $ingredient->id }}" class="hidden"
                                              action="{{ route('admin.ingredients.destroy',$ingredient) }}">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </tr>
                                @empty
                                    <tr class="text-center">
                                        <th colspan="20">No data found</th>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                        <div class="card-footer">
                            {{ $ingredients->links('back-end.layout.partials.pagination') }}
                        </div>

                    </div>
                </div>
            </div>
            <!--Row-->

        </div>
    </div>
@endsection