routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\AboutUsController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\HealthBenefitController;
use App\Http\Controllers\Admin\IngredientController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\WellbeingController;
use App\Http\Controllers\CKeditorController;
use App\Http\Controllers\Frontend\FrontendController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/test', function () {
    return view('back-end.dashboard');
});

Route::group(['as' => 'front_end.'], function () {
    Route::get('/', [FrontendController::class, 'home'])->name('home');
    Route::get('/drinks', [FrontendController::class, 'products'])->name('drinks');
    Route::get('/drink/{slug}', [FrontendController::class, 'product_detail'])->name('drinks.detail');
    Route::get('/stores', [FrontendController::class, 'store'])->name('stores');
    Route::get('/vibe', [FrontendController::class, 'vibe'])->name('vibe');
    Route::get('/about-us', [FrontendController::class, 'about_us'])->name('about_us');
    Route::get('/contact-us', [FrontendController::class, 'contact'])->name('contact');
    Route::get('/jobs', [FrontendController::class, 'jobs'])->name('jobs');

    Route::get('/privacy-policy', [FrontendController::class, 'privacy'])->name('privacy_policy');
    Route::get('/terms-and-conditions', [FrontendController::class, 'term_and_condition'])->name('term');

    Route::group(['prefix' => 'news'], function () {
        Route::get('/', [FrontendController::class, 'posts'])->name('news.index');
        Route::get('/{slug}', [FrontendController::class, 'postShow'])->name('news.detail');
    });

    Route::group(['prefix' => 'wellbeing'], function () {
        Route::get('/', [FrontendController::class, 'wellbeing'])->name('wellbeing.index');
        Route::get('/{slug}', [FrontendController::class, 'wellbeing_detail'])->name('wellbeing.detail');
    });

    Route::group(['prefix' => 'franchising', 'as' => 'franchising.'], function () {
        Route::get('/', [FrontendController::class, 'franchising'])->name('index');
    });
});


Route::group(['middleware' => ['auth'], 'prefix' => 'dashboard', 'as' => 'admin.'], function () {
    Route::get('/', function () {
        return view('back-end.dashboard');
    })->name('dashboard');
    Route::resource('categories', CategoryController::class);
    Route::resource('benefits', HealthBenefitController::class);
    Route::resource('ingredients', IngredientController::class);
    Route::resource('products', ProductController::class);
    Route::resource('posts', PostController::class);
    Route::resource('wellbeing', WellbeingController::class);
    Route::resource('about', AboutUsController::class);
    Route::resource('users', UserController::class);

    Route::get('profile', [ProfileController::class, 'profile'])->name('profile');
    Route::put('profile', [ProfileController::class, 'update_profile'])->name('profile.update');
    Route::post('password', [ProfileController::class, 'change_password'])->name('profile.change_password');

    Route::resource('settings', SettingController::class)->except(['delete']);

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {

        Route::get('{page}/setting', [PageController::class, 'index'])->name('index');
        Route::put('{page}/setting', [PageController::class, 'update'])->name('update');

        Route::get('/vibe', [PageController::class, 'vibe_page'])->name('vibe');
        Route::put('/vibe', [PageController::class, 'update_vibe_page'])->name('vibe.update');

        Route::resource('{page}/faq', FaqController::class);
    });
});

Route::post('ckeditor/upload', [CKeditorController::class, 'upload'])->name('ckeditor.image-upload');


Auth::routes([
    'login' => true,
    'register' => false,
    'reset' => false
]);

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Post extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = ['id'];

    protected $attributes = [
        'status' => 1,
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = Str::title($value);
        $this->attributes['slug'] = preg_replace('/\s+/u', '-', trim(Str::lower($value)));
    }


}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\PostRequest;
use App\Http\Traits\ImageUploadTrait;
use App\Models\Post;

class PostController extends Controller
{
    use ImageUploadTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::with('user')->orderBy('id', 'desc')->paginate(10);
        return view('back-end.posts.index', [
            'posts' => $posts
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $post = new Post();
        return view('back-end.posts.create', [
            'post' => $post
        ]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        Post::create([
            'user_id' => auth()->id(),
            'title' => $request->title,
            'description' => $request->description,
            'short_description' => $request->short_description,
            'image' => $this->upload($request->file('image')),
            'home_image' => $this->upload($request->file('home_image')),
            'status' => isset($request->status)
        ]);
        return redirect()->route('admin.posts.index')->with('success', 'Post created successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('back-end.posts.show', [
            'post' => $post
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('back-end.posts.edit', ['post' => $post]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, Post $post)
    {
        $post->update([
            'title' => $request->title,
            'description' => $request->description,
            'short_description' => $request->short_description,
            'status' => isset($request->status)
        ]);

        if ($request->file('image')) {
            $imageName = $this->updateImage($post->image, $request->file('image'));
            $post->update(['image' => $imageName]);
        }

        if ($request->file('home_image')) {
            $imageName = $this->updateImage($post->home_image, $request->file('home_image'));
            $post->update(['home_image' => $imageName]);
        }

        return redirect()->route('admin.posts.index')->with('success', 'Post updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->route('admin.posts.index')->with('success', 'Post deleted successfully');
    }
}

resources/views/back-end/posts/create.blade.php
@extends('back-end.layout.app')


@section('title,14 Feb','Add Post')

@section('content')
    <div id="content">
        <div class="container-fluid" id="container-wrapper">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">New Post</h1>
                <ol class="breadcrumb">
                    <a href="{{ route('admin.posts.index') }}" class="btn btn-primary">All Posts</a>
                </ol>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <!-- Form Basic -->
                    <div class="card mb-4">
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">New Post</h6>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('admin.posts.store') }}"
                                  enctype="multipart/form-data">
                                @csrf
                                @include('back-end.posts.form')
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
            <!--Row-->
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('admin/js/image-preview.js') }}"></script>
    <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
    <script>
        $(document).ready(function () {
            $('.ckeditor').ckeditor();
        });
    </script>

@endpush

resources/views/back-end/posts/edit.blade.php
@extends('back-end.layout.app')


@section('title,14 Feb','Edit Posts')

@section('content')
    <div id="content">
        <div class="container-fluid" id="container-wrapper">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Edit Post</h1>
                <ol class="breadcrumb">
                    <a href="{{ route('admin.posts.index') }}" class="btn btn-primary">All Posts</a>
                </ol>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <!-- Form Basic -->
                    <div class="card mb-4">
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">Edit Post</h6>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('admin.posts.update', $post) }}"
                                  enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                @include('back-end.posts.form')
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
            <!--Row-->
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('admin/js/image-preview.js') }}"></script>
    <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
    <script>
        $(document).ready(function () {
            $('.ckeditor').ckeditor();
        });
    </script>

@endpush

resources/views/back-end/posts/form.blade.php
<div class="form-group">
    <label for="validationServer03">Name</label>
    <input type="text" name="title"
           class="form-control  @error('title') is-invalid @enderror" value="{{ old('title', $post->title) }}">
    @error('title')
    <div class="invalid-feedback">
        {{ $message }}
    </div>
    @enderror
</div>

<div class="form-group">
    <label for="validationServer03">Short Description</label>
    <textarea type="text" name="short_description"
              class="form-control ckeditor  @error('short_description') is-invalid @enderror"
              value="{{ old('short_description', $post->description) }}">{{ old('short_description', $post->short_description) }}</textarea>
    @error('short_description')
    <div class="invalid-feedback">
        {{ $message }}
    </div>
    @enderror
</div>

<div class="form-group">
    <label for="validationServer03">Description</label>
    <textarea type="text" name="description"
              class="form-control ckeditor  @error('description') is-invalid @enderror"
              value="{{ old('description', $post->description) }}">{{ old('description', $post->description) }}</textarea>
    @error('description')
    <div class="invalid-feedback">
        {{ $message }}
    </div>
    @enderror
</div>

<div class="form-row form-group">
    <div class="col">
        <div class="custom-file">
            <input type="file" name="image" class="custom-file-input @error('image') is-invalid @enderror images"
                   id="image"
                   data-preview="#image_preview">
            <label class="custom-file-label" for="customFile">Image</label>
            @error('image')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
        </div>
        <img class="img-thumbnail mt-3" src="{{ asset('images/' . $post->image) }}" id="image_preview"
             alt="Image Preview">
    </div>
    <div class="col">
        <div class="custom-file">
            <input type="file" class="custom-file-input @error('home_image') is-invalid @enderror images"
                   name="home_image"
                   id="home_image" data-preview="#home_image_preview">
            <label class="custom-file-label" for="home_image">Home Image (PNG)</label>
            @error('home_image')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
        </div>
        <img class="img-thumbnail mt-3" src="{{ asset('images/' . $post->home_image ) }}" id="home_image_preview"
             alt="Image Preview">
    </div>
</div>

<div class="form-group">
    <div class="custom-control custom-checkbox">
        <input type="checkbox" name="status"
               {{ $post->status ==1 ? 'checked' : '' }} class="custom-control-input @error('status') is-invalid @enderror"
               id="status">
        <label class="custom-control-label" for="status">Status</label>
        @error('status')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>

</div>

resources/views/back-end/posts/index.blade.php
@extends('back-end.layout.app')


@section('title,14 Feb','All Posts')


@section('content')
    <div id="content">
        <div class="container-fluid" id="container-wrapper">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">All Posts</h1>
                <ol class="breadcrumb">
                    <a href="{{ route('admin.posts.create') }}" class="btn btn-primary">New Post</a>
                </ol>
            </div>

            <div class="row">
                <div class="col-lg-12 mb-4">
                    <!-- Simple Tables -->
                    <div class="card">
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">All Posts</h6>
                        </div>
                        <div class="table-responsive">
                            <table class="table align-items-center table-flush">
                                <thead class="thead-light">
                                <tr>
                                    <th>#</th>
                                    <th>Image</th>
                                    <th>Title</th>
                                    <th>status</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($posts as $post)
                                    <tr>
                                        <td class="align-middle">{{ ++$loop->index }}</td>
                                        <td>
                                            <img class="img-thumbnail" width="80"
                                                 src="{{ asset('images/' . $post->image) }}"
                                                 alt="Image">
                                        </td>
                                        <td class="align-middle">{{ $post->title }}</td>
                                        <td class="align-middle">
                                            @if($post->status ==1 )
                                                <span class="badge badge-success">active</span>
                                            @else
                                                <span class="badge badge-danger">inactive</span>
                                            @endif

                                        </td>
                                        <td class="align-middle">
                                            <a href="{{ route('admin.posts.show', $post) }}"
                                               class="btn btn-sm btn-success">Show</a>
                                            <a href="{{ route('admin.posts.edit', $post) }}"
                                               class="btn btn-sm btn-primary">Edit</a>
                                            <a onclick="if(confirm('Are you sure?')){
                                                document.getElementById('delete-{{$post->id}}').submit()
                                                }" class="btn btn-sm btn-danger">Delete</a>
                                        </td>
                                        <form method="POST" id="delete-{{ $post->id }}" class="hidden"
                                              action="{{ route('admin.posts.destroy',$post) }}">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                    </tr>
                                @empty
                                    <tr class="text-center">
                                        <th colspan="20">No data found</th>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                        <div class="card-footer">
                            {{ $posts->links('back-end.layout.partials.pagination') }}
                        </div>
                    </div>
                </div>
            </div>
            <!--Row-->

        </div>
    </div>
@endsection

resources/views/back-end/posts/show.blade.php
@extends('back-end.layout.app')


@section('title,14 Feb','Show Post')

@section('content')
    <div id="content">
        <div class="container-fluid" id="container-wrapper">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Show Post</h1>
                <ol class="breadcrumb">
                    <a href="{{ route('admin.posts.index') }}" class="btn btn-primary">All Posts</a>
                </ol>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <!-- Form Basic -->
                    <div class="card mb-4">
                        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                            <h4 class="m-0 font-weight-bold text-primary">Title: {{ $post->title }}</h4>
                        </div>
                        <div class="card-body">
                            {!! $post->description !!}
                        </div>
                    </div>

                </div>
            </div>
            <!--Row-->
        </div>
    </div>
@endsection

@push('js')

@endpush